### ISSUE TITLE
BleMidiClient_esp32.h not exist

### ISSUE THREAD

**Issue by alf45tar** [lathoub/Arduino-BLE-MIDI#11]
Compile error on line

https://github.com/lathoub/Arduino-BLE-MIDI/blob/940c1aa886da84f843834d3afc24ebe3faf8a910/src/BleMidi.h#L15

Please replace BleMidiClient_esp32.h with BleClient_esp32.h or rename the file.

**Comment by lathoub** [comment]
fixed, thank you @alf45tar
