### ISSUE TITLE
Change BLE device name at runtime with feat/2.0.0

### ISSUE THREAD

**Issue by alf45tar** [lathoub/Arduino-BLE-MIDI#13]
Is it possible to change the BLE device name at runtime with feat/2.0.0?

Thanks
alf45tar

**Comment by catskull** [comment]
Looking at the source code, I found this line: https://github.com/lathoub/Arduino-BLE-MIDI/blob/feat/2.0.0/src/BLE-MIDI.h#L194

Instead of `BLEMIDI_CREATE_DEFAULT_ESP32_INSTANCE()`

just do

`BLEMIDI_CREATE_ESP32_INSTANCE("Custom Name")`

Tested working in MacOS.
