### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by BruceWayne-cpu** [lathoub/Arduino-BLE-MIDI#16]
Hi, I downloaded the repository and tried it as a local library in my Platformio project but couldnt get it to work. It seems that the "common/midiCommon.h" file is missing. Any ideas on how to get it to work?
 Thanks in advice 
Bruno

**Comment by lathoub** [comment]
Use [branch feat/2.0.0](https://github.com/lathoub/Arduino-BLE-MIDI/tree/feat/2.0.0)
