### ISSUE TITLE
Not showing any BLE-MIDI device with ESP32-CAM

### ISSUE THREAD

**Issue by pabolojo** [lathoub/Arduino-BLE-MIDI#23]
Hi!, I have been trying to get your library to work for a couple of days without success. I have and ESP32-CAM board (ESP32-S) and I have tried your example sketch and tweak it with small variations but I haven't managed to get any device shown in the "MIDI BLE Connect" app. Am I doing something wrong? Maybe my setup is not correct?
Appreciate your help :)

**Comment by lathoub** [comment]
I don;t have a ESP32-CAM, but a ESP32 DevKit is working A-OK. 
Do you still have the issue with the current code?
