### ISSUE TITLE
Only Channel 0 messages are transmitted

### ISSUE THREAD

**Issue by lotrasoft** [lathoub/Arduino-BLE-MIDI#24]
I have a weird issue. Only channel 0 messages are transmitted to ESP32; and, for all those messages, the channel number received on ESP32 is 1. Other channels are completely ignored by the library.

I don't have this issue with other libraries.

**Comment by zeevj** [comment]
Just add the channel number you want to MIDI.begin();
channel 4:
MIDI.begin(4);

**Comment by lotrasoft** [comment]
Thanks, how can I enable it for all channels?

**Comment by lathoub** [comment]
Passing 0 indeed does the trick, (or use `MIDI_CHANNEL_OMNI`)
See https://github.com/FortySevenEffects/arduino_midi_library/blob/da8ca5e69a63e1cbf2433e070b87e6f09a709b85/src/midi_Defs.h#L43
