### ISSUE TITLE
Devise not advertising

### ISSUE THREAD

**Issue by BruceWayne-cpu** [lathoub/Arduino-BLE-MIDI#26]
I'm trying to use this library with a Wemos D1 mini 32, but when I try with NimBle example it compiles and uploads without errors but it does not show up in my BLE scanner.
However when I try with the Basic example with "#include <hardware/BLEMIDI_ESP32.h>" it throws:

![Screenshot from 2021-02-09 01-05-55](https://user-images.githubusercontent.com/70959911/107314330-289b9400-6a73-11eb-9f29-4907cc38f531.png)

**Comment by lathoub** [comment]
I don't have any Wemos D1 hardware, so can't compare.  The Wemos D1 mini is ESP8266 based, not? From the log: **device not support** error, that would explain why it does not compile using the Esp32 header.

**Comment by BruceWayne-cpu** [comment]
The Wemos D1 mini 32 is esp32 based. The strange thing is that I've already used the esp 32 BLE libraries successfully in this same board. I mean:  <BLEDevice.h>, <BLEUtils.h>, <BLEServer.h>, <BLE2902.h> they work fine, but when using <hardware/BLEMIDI_ESP32.h> it throws that error...

**Comment by BruceWayne-cpu** [comment]
Whats interesting is that when I look into the libdeps folder in the project that uses  <BLEDevice.h>, <BLEUtils.h>, <BLEServer.h>, <BLE2902.h>, there are no dependencies related to BLE, maybe they are core drivers? 
But when I look into the libdeps folder in the BLE-MIDI project there is an ArduinoBLE library.

**Comment by BruceWayne-cpu** [comment]
Why is it ArduinoBLE a dependency?

**Comment by BruceWayne-cpu** [comment]
Ok, so I removed the ArduinoBLE library that was automatically installed by Platformio/Arduino IDE (tried with both) and it works fine now. Both the NimBle version and the normal one. Maybe consider removing that lib dep? thank you for your good work!

**Comment by lathoub** [comment]
if you use NimBLE and the ESP32 BT stack, you indeed do not need ArduinoBLE. But if you use the Arduino Nano 33 BLE, you do need the ArduinoBLE stack. Unfortunately, the IDE does not allow for conditional dependencies.

A solution to avoid the conflict would be to remove the dependencies and have them installed manually - depending on the platform and prefered BLE stack.

**Comment by BruceWayne-cpu** [comment]
Yes, i think that could be a solution.

**Comment by sdstronic** [comment]
Hi , working on the same configuration, i post here
My ESP32 is ok on Midi with full stack BLE, but very high memory consomption...
I try BLE-MIDI and after manage dependency issue, all seems compiled fine
but i get: E NimBLEAdvertising: "Advertisement data length exceded" on the MIDI.begin();
any idee ?

**Comment by AlexFundorin** [comment]
I have the same issue with generic ESP32 board from Aliexpress.
It was working with ArduinoBLE, but I decided to try your library today.
The same errors, after I initialized the library like this: 
```
#include <BLEMIDI_Transport.h>
#include <hardware/BLEMIDI_ESP32.h>
```
Dunno why  is says "Unsupported board" to a "esp32doit-devkit-v1".

**Comment by lathoub** [comment]
https://github.com/lathoub/Arduino-BLE-MIDI/issues/31

**Comment by lathoub** [comment]
stale
