### ISSUE TITLE
No BLE advertisement when using example sketch

### ISSUE THREAD

**Issue by joeybab3** [lathoub/Arduino-BLE-MIDI#31]
I may just be missing something obvious but when running the example sketch on the ESP32 dev board I don't see any device advertised. 

I do see a device advertised when using the NIM-BLE examples so I don't think it's an issue with my board.

Any ideas?

**Comment by joeybab3** [comment]
Interestingly enough it does appear to be advertising but it does not show up on any device I use to try and connect. 

Using nRF connect I can see the device advertising though. Does anyone know what might be causing this?

**Comment by lathoub** [comment]
I updated the code the re-advertise after disconnect - can you try again?

**Comment by lathoub** [comment]
@joeybab3 pls check

**Comment by Theo428** [comment]
I am having the same issue with a nodemcu-32s board. I just downloaded the latest version of the library using library manager. I do not have a way to monitor if the device is broadcasting or not like the nRF mentioned above but it does advertise with the nimBLE example server but does not with the example sketches provided. I don't see it on either windows 11 or android if that makes any difference. I don't have any other devices to test on.

**Comment by lathoub** [comment]
Can you try by downloading from this site (not using the library manager, but download the zip file). I was awaiting the feedback from @joeybab3 before I publish to the Arduino catalog

**Comment by Theo428** [comment]
> Can you try by downloading from this site (not using the library manager, but download the zip file). I was awaiting the feedback from @joeybab3 before I publish to the Arduino catalog

It appears to work now. I can see the device in both windows and on my phone and I connect and receive the data.

**Comment by joeybab3** [comment]
> 

I will try it asap, I am in school now so I don't have as easy access to my development stuff

**Comment by lathoub** [comment]
paging @joeybab3

**Comment by lathoub** [comment]
@joeybab3 last call

**Comment by joeybab3** [comment]
I still don't have anything to test it on at the moment as I am in school. Feel free to close the issue and I will reopen it if I can test it at a later time and find that the issue is still existing.
