### ISSUE TITLE
Compiling error due to repeated end() method

### ISSUE THREAD

**Issue by alf45tar** [lathoub/Arduino-BLE-MIDI#35]
The end() method is declared 2 times in BLEMIDI_Transport.h in the exact same way (line 51 and 56) and the compile error is "end() cannot be overloaded"

https://github.com/lathoub/Arduino-BLE-MIDI/blob/697e0d40b0ff6b7b6cadc212df98151bb8d9ddaf/src/BLEMIDI_Transport.h#L51

https://github.com/lathoub/Arduino-BLE-MIDI/blob/697e0d40b0ff6b7b6cadc212df98151bb8d9ddaf/src/BLEMIDI_Transport.h#L56

**Comment by lathoub** [comment]
Fixed! Thank you @alf45tar 
(Not sure how it ended up twice in the code)
