### ISSUE TITLE
Namespace symbols

### ISSUE THREAD

**Issue by alf45tar** [lathoub/Arduino-BLE-MIDI#38]
Should SERVICE_UUID name-spaced?

There is a conflict when used with https://github.com/improv-wifi/sdk-cpp/issues/4#issuecomment-988177924

Thanks
alf45tar

**Comment by lathoub** [comment]
Good point @alf45tar 

at first sight, I suggest to move

https://github.com/lathoub/Arduino-BLE-MIDI/blob/4724511fa88b08144b4485328d6d5d650926e788/src/BLEMIDI_Defs.h#L5-L10

to 

https://github.com/lathoub/Arduino-BLE-MIDI/blob/4724511fa88b08144b4485328d6d5d650926e788/src/BLEMIDI_Transport.h#L16

Can you try if that works? If so, create a PR and I'll accept it

**Comment by lathoub** [comment]
thanks @alf45tar
