### ISSUE TITLE
Is it posible receive/send raw data between BLEMIDI and Serial port?

### ISSUE THREAD

**Issue by henriquegmatos** [lathoub/Arduino-BLE-MIDI#44]
Is it possible to receive and send raw midi data from BLEMIDI to/from a serial port without having to deal with handle like setHandleNoteOn?

i just like to transfer data between blemidi and serial port without needing to know what type of midi data it is, including sysex data. It is possible?

I am using TTGO ESP32 MINI32 v1.4 LilyGO

best regards

**Comment by lathoub** [comment]
The `setHandleMessage` callback from the underlying [MIDI library](https://github.com/FortySevenEffects/arduino_midi_library) might be your best option

I haven't tried the below on actual hardware, but is a good starting point:
```cpp
BleMIDI.setHandleMessage([](const MidiMessage& msg)
{
    SerialMIDI.send(msg);
})
```

**Comment by henriquegmatos** [comment]
thanks
