### ISSUE TITLE
Error compiling for board DOIT ESP32 DEVKIT V1.

### ISSUE THREAD

**Issue by Protezhe** [lathoub/Arduino-BLE-MIDI#47]
Hi! I have a problem... All examples not compilling

`In file included from C:\Users\Alf\Documents\Arduino\libraries\Arduino-BLE-MIDI-master\examples\MidiBle\MidiBle.ino:1:0:
C:\Users\Alf\Documents\Arduino\libraries\Arduino-BLE-MIDI-master\src/BLEMIDI_Transport.h: In member function 'void bleMidi::BLEMIDI_Transport<T, _Settings>::endTransmission()':
C:\Users\Alf\Documents\Arduino\libraries\Arduino-BLE-MIDI-master\src/BLEMIDI_Transport.h:89:40: error: 'SystemExclusiveEnd' was not declared in this scope
         if (mTxBuffer[mTxIndex - 1] == SystemExclusiveEnd)
                                        ^
In file included from C:\Users\Alf\Documents\Arduino\libraries\MIDI_Library\src/MIDI.h:259:0,
                 from C:\Users\Alf\Documents\Arduino\libraries\Arduino-BLE-MIDI-master\src/BLEMIDI_Transport.h:7,
                 from C:\Users\Alf\Documents\Arduino\libraries\Arduino-BLE-MIDI-master\examples\MidiBle\MidiBle.ino:1:
C:\Users\Alf\Documents\Arduino\libraries\MIDI_Library\src/MIDI.hpp: In instantiation of 'void midi::MidiInterface<SerialPort, _Settings>::begin(midi::Channel) [with SerialPort = bleMidi::BLEMIDI_Transport<bleMidi::BLEMIDI_ESP32>; _Settings = bleMidi::MySettings; midi::Channel = unsigned char]':
C:\Users\Alf\Documents\Arduino\libraries\Arduino-BLE-MIDI-master\examples\MidiBle\MidiBle.ino:20:14:   required from here
C:\Users\Alf\Documents\Arduino\libraries\MIDI_Library\src/MIDI.hpp:91:5: error: no matching function for call to 'bleMidi::BLEMIDI_Transport<bleMidi::BLEMIDI_ESP32>::begin(const long int&)'
     mSerial.begin(Settings::BaudRate);
     ^
In file included from C:\Users\Alf\Documents\Arduino\libraries\Arduino-BLE-MIDI-master\examples\MidiBle\MidiBle.ino:1:0:
C:\Users\Alf\Documents\Arduino\libraries\Arduino-BLE-MIDI-master\src/BLEMIDI_Transport.h:57:10: note: candidate: void bleMidi::BLEMIDI_Transport<T, _Settings>::begin() [with T = bleMidi::BLEMIDI_ESP32; _Settings = bleMidi::DefaultSettings]
     void begin()
          ^
C:\Users\Alf\Documents\Arduino\libraries\Arduino-BLE-MIDI-master\src/BLEMIDI_Transport.h:57:10: note:   candidate expects 0 arguments, 1 provided
Multiple libraries were found for "MIDI.h"
 Used: C:\Users\Alf\Documents\Arduino\libraries\MIDI_Library
 Not used: C:\Users\Alf\Documents\Arduino\libraries\arduino_midi_library-master
exit status 1
Error compiling for board DOIT ESP32 DEVKIT V1.
`

**Comment by lathoub** [comment]
Please provide a minimal sketch or reference to an example. I'm also using the DOIT ESP32 DEVKIT V1 for my development and all works just fine.
